### ISSUE TITLE
ics client crashes when trying to get info while LIBICSNEO_FWBIN_PATH is set

### ISSUE THREAD

**Issue by bigcmos** [intrepidcs/ics-cli#1]
When setting `LIBICSNEO_FWBIN_PATH` the ics client core dumps.  I've tried with the full path and relative path to the fw file.

```
$ ./ics-cli/bin/ics --version
ics-cli version: v0.0.0
$ sudo setcap cap_net_raw+eip ics-cli/bin/ics
$ export LIBICSNEO_FWBIN_PATH=fw.bin
$ ./ics-cli/bin/ics info AB0095
Current firmware versions:
    ZCHIP    12.2

Available firmware versions:
    ZCHIP    v12.2

Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x0000000000426355 in ics::cli::InfoCmd::evaluate() ()
#1  0x000000000041ebe4 in ics::cli::App::input(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#2  0x000000000041a367 in main ()
```

Without setting the variable the client does not crash but requests that the environment variable be set.

```
$  ./ics-cli/bin/ics info AB0095
Current firmware versions:
    ZCHIP    12.2

Available firmware versions:
Warning: Failed to load fw.bin
Hint: Make sure to set "LIBICSNEO_FWBIN_PATH" environment variable to your fw.bin file location
```

**Comment by yyassine-intrepidcs** [comment]
This was due to a message timing out and error checking not being done properly, it should be good in v0.1.0. [Latest](https://github.com/intrepidcs/ics-cli/releases/latest)
